I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_2.rpy", line 11, in script
    arc "Hey [n]!!"
KeyError: u'n'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_2.rpy", line 11, in script
    arc "Hey [n]!!"
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/home/thatchedroof/renpy-7.4.11-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'n'

Linux-5.15.5-76051505-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
vs DeO 1.0
Sat Dec 18 17:20:56 2021
