I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_2.rpy", line 44, in script
    menu d2_school_navigate_menu:
  File "game/day_2.rpy", line 67, in <module>
    "{b}Dismissal{\b}" if d2_math_class_v:
NameError: name 'd2_math_class_v' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_2.rpy", line 44, in script
    menu d2_school_navigate_menu:
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/ast.py", line 1683, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/exports.py", line 1028, in menu
    condition = renpy.python.py_eval(condition)
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/python.py", line 2266, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/thatchedroof/Documents/renpy-7.4.8-sdk/renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/day_2.rpy", line 67, in <module>
    "{b}Dismissal{\b}" if d2_math_class_v:
NameError: name 'd2_math_class_v' is not defined

Linux-5.13.0-21-generic-x86_64-with-debian-11.0
Ren'Py 7.4.8.1895
vs DeO 1.0
Tue Nov 23 16:20:29 2021
